module.exports = [
    {
      id: '9ec1dbe1',
      name: 'coats_jackets',
      category: ['blazers', 'jackets', 'coats'],
      orders: [],
      filters: [
        {attribute: 'category', value: 'blazers'},
        {attribute: 'category', value: 'jackets'},
        {attribute: 'category', value: 'coats'},
      ],
    },
    {
      id: 'a056e8581',
      name: 'tops',
      category: ['cardigans_and_shrugs', 'sweaters', 'sweatshirts', 'tops'],
      orders: [
        {type: 't_shirts'},
        {type: 'polo_shirts'},
        {type: 'blouses'},
        {type: 'shirts'},
        {type: 'tank_tops'},
      ],
      filters: [
        {attribute: 'type', value: 't_shirts'},
        {attribute: 'type', value: 'polo_shirts'},
        {attribute: 'type', value: 'blouses'},
        {attribute: 'type', value: 'shirts'},
        {attribute: 'type', value: 'tank_tops'},
        {attribute: 'category', value: 'cardigans_and_shrugs'},
        {attribute: 'category', value: 'sweaters'},
        {attribute: 'category', value: 'sweatshirts'},
      ],
    },
    {
      id: 'f845bd0d',
      name: 'lows',
      category: ['pants', 'jeans', 'skirts', 'shorts'],
      orders: [],
      filters: [
        {attribute: 'category', value: 'pants'},
        {attribute: 'category', value: 'jeans'},
        {attribute: 'category', value: 'skirts'},
        {attribute: 'category', value: 'shorts'},
      ],
    },
    {
      id: '8ce41238',
      name: 'one_piece',
      category: ['dresses', 'jumpsuits', 'rompers'],
      orders: [],
      filters: [
        {attribute: 'category', value: 'dresses'},
        {attribute: 'category', value: 'jumpsuits'},
        {attribute: 'category', value: 'rompers'},
      ],
    },
    {
      id: 'a8942a82',
      name: 'shoes',
      category: ['footwear'],
      orders: [
        {type: 'boots'},
        {type: 'sandals'},
        {type: 'mules'},
        {type: 'flip_flops'},
        {type: 'sneakers'},
        {type: 'athletic'},
        {type: 'formal_shoes'},
        {type: 'pumps'},
        {type: 'loafers'},
        {type: 'wedges'},
        {type: 'type'},
        {type: 'type'},
        {type: 'sliders'},
        {type: 'slipons'},
      ],
      filters: [
        {attribute: 'type', value: 'boots'},
        {attribute: 'type', value: 'boots'},
        {attribute: 'type', value: 'sandals'},
        {attribute: 'type', value: 'mules'},
        {attribute: 'type', value: 'flip_flops'},
        {attribute: 'type', value: 'sneakers'},
        {attribute: 'type', value: 'athletic'},
        {attribute: 'type', value: 'formal_shoes'},
        {attribute: 'type', value: 'pumps'},
        {attribute: 'type', value: 'loafers'},
        {attribute: 'type', value: 'wedges'},
        {attribute: 'type', value: 'flats'},
        {attribute: 'type', value: 'ballet_flats'},
        {attribute: 'type', value: 'sliders'},
        {attribute: 'type', value: 'slipons'},
      ],
    },
    {
      id: '17f9a04a',
      name: 'bags',
      category: ['bags'],
      orders: [
        {type: 'clutches'},
        {type: 'shoulder_bag'},
        {type: 'satchel'},
        {type: 'totes'},
        {type: 'gym_bag'},
        {type: 'messenger_bag'},
        {type: 'backpacks'},
        {type: 'briefcase'},
        {type: 'crossbody'},
        {type: 'bucketbag'},
        {type: 'hobos'},
        {type: 'duffle'},
      ],
      filters: [
        {attribute: 'type', value: 'clutches'},
        {attribute: 'type', value: 'shoulder_bag'},
        {attribute: 'type', value: 'satchel'},
        {attribute: 'type', value: 'totes'},
        {attribute: 'type', value: 'gym_bag'},
        {attribute: 'type', value: 'messenger_bag'},
        {attribute: 'type', value: 'backpacks'},
        {attribute: 'type', value: 'briefcase'},
        {attribute: 'type', value: 'crossbody'},
        {attribute: 'type', value: 'bucketbag'},
        {attribute: 'type', value: 'hobos'},
        {attribute: 'type', value: 'duffle'},
      ],
    },
    {
      id: '8d0d943e',
      name: 'other',
      category: ['jewellery', 'outerwear', '', null, undefined],
      orders: [],
      filters: []
    },
  ];
  